# Generated by Django 3.2 on 2024-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
